blog/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('story.urls'))
]

story/urls.py
from django.contrib import admin
from django.urls import path
from.import views

app_name='story'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.story_list, name='story_list'),
    path('search/',views.search_story, name='story_search'),
    path('<slug:category_slug>', views.story_list, name='story_by_category'),
    path('<int:id>/', views.story_detail, name='story_detail'),
    path('search/',views.search_story, name='story_search')

]

story/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=150,db_index=True)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering=('-name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('story:story_by_category',args=[self.slug])


class Story(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body = models.TextField(db_index=True)
    des = models.TextField(blank=True)
    publish = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('story:story_detail', args=[self.id,])

# Create your models here.

story/views.py
from django.shortcuts import render, get_object_or_404,redirect
from.models import Story,Category
from django.core.paginator import PageNotAnInteger,Paginator,EmptyPage
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate
from django.contrib import messages
import random


# Create your views here.



def story_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    story = Story.objects.all()
    print("leg of all story ",len(story))
    paginator=Paginator(story,4)
    page=request.GET.get('page')
    try:
        story=paginator.page(page)
    except PageNotAnInteger:
        story=paginator.page(1)
    except EmptyPage:
        story=paginator.page(paginator.num_pages)
    if category_slug:
        story=Story.objects.all()
        category = get_object_or_404(Category,slug=category_slug)
        story = story.filter(category=category)
        paginator = Paginator(story,2)
        page = request.GET.get('page')
        try:
            story = paginator.page(page)
        except PageNotAnInteger:
            story = paginator.page(1)
        except EmptyPage:
            story = paginator.page(paginator.num_pages)
    all_story = list(Story.objects.all())
    recent_story = random.sample(all_story,2)
    return render(request,"story_list.html",{'categories':categories,'category':category,'story':story,'page':page,'recent_story':recent_story,})


def story_detail(request,id):
    story=get_object_or_404(Story,id=id)
    all_story = list(Story.objects.exclude(id=id))
    like_story = random.sample(all_story,2)

    return render(request,'story_detail.html',{'story':story,'like_story':like_story,})


def search_story(request):
    query=None
    results=[]
    if request.method =='GET':
        query = request.GET.get("search")
        results = Story.objects.filter(Q(title__icontains=query)| Q(body__icontains=query))
        return render(request,'search.html',{'query':query,'results':results})

templates/base.html
<!doctype html>
<html lang="en">
  <head>
      <style>
          body{
              min-height: 100vh;
              margin-bottom: -100px;
          }
          .sticky-footer{
              position: sticky;
              top: 100%;

          }
      </style>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block title %}
        <title>Story Book</title>
    {% endblock %}


  </head>
  <body>
  <nav class ="navbar navbar-dark bg-dark">
    <nav class ="container">
        <span class ="navbar-brand mb-0 h1"> Story Book </span>
    </nav>
  </nav>
  {% block body %}

  {% endblock %}

  <!-- Footer -->
<div class="sticky-footer">
<footer class="text-center text-lg-start bg-dark text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-4 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-4">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-3">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>@TR Books
          </h6>
          <p>
            Here all types of stories to write . search and read stories.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-3">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-3">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-3">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Contact
          </h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
</div>
<!-- Footer -->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/pagination.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}
<div class="">
    <span class="">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="">
            page{{ page.number }} of {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>
{% endblock %}
</body>
</html>

templates/search.html
{% extends 'base.html' %}


    {% block title %}<title>search story</title>{% endblock %}

{% block body %}
    <div class="container">
        <h1>this is search page</h1>
    {% if query %}
        <h3>
            {% with results.count as total_results %}Found {{ total_results }} results{% endwith %}
        </h3>
        {% for x in results %}
            <div class="mt-3">
                <a href="{{ x.get_absolute_url }}">
                    <h2 >{{ x.title }}</h2>
                </a>
                <p>{{ x.des }}</p>
            </div>
        {% empty %}
            <h3>there is no query</h3>
        {% endfor %}
    {% else %}
        <h3>please search for right query ! it's doesn't have here...!</h3>
    {% endif %}
    </div>
{% endblock %}

templates/story_detail.html
{% extends 'base.html' %}


    {% block title %}
        <title></title>
    {% endblock %}


{% block body %}
    <div class="container">
        <h1 >DFETAIL PAGE OF STORY</h1>
        <h2 class="text-center">STORY NAME : {{ story.title }}</h2>
        <p class="lead">STORY: {{ story.body|safe }}</p>
    </div>
    <hr>
    <div class="container">
        <h2>YOU MAY ALSO LIKE:</h2>
        {% for x in like_story %}
            <a href="{{ x.get_absolute_url }}"><h5>{{ x.title }}</h5></a>
        {% endfor %}
    </div>
{% endblock %}

templates/story_list.html
{% extends 'base.html' %}

{% block title %}
    <title>story book</title>
{% endblock %}

{% block body %}
    <div class="pricing-header px-3 py-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Story Book</h1>
        <p class="lead">You Can Find Here Some Short Stories</p>

    </div>
    <div class="container mt-3 ">
    <div class="card bg-dark text-white mt-3">
        <hr><h2 class="text-center px-3 py-3 ">Categories</h2><hr>
        <ul class="list-group">
            <li class="list-group-item list-group-item-action  list-group-item-dark">
                <h3><a href="{% url 'story:story_list' %}" class="link-danger">All-Stories</a></h3>
                {% for x in categories %}
                    <li class="list-group-item list-group-item-action  list-group-item-success">
                        <h4><a href="{{ x.get_absolute_url }} " class="link-dark" >{{ x.name }}</a></h4>
                    </li>
                {% endfor %}
            </li>
        </ul>
    </div>
    <div><hr>

        <form action="{% url 'story:story_search' %}" class="form-inline" method="get">
            <div class="form-group mx-sm-3 mb-2">
                <h3>{% if category%}{{ category.name }}{% else %}All-Stories{% endif %}</h3><hr>
            </div>
            <div class="form-group mx-sm-3 mb-2">
                <label class="sr-only"><h4> Search </h4></label>
                <input name="search" class="form-control">
            </div>
            <button type="submit" class="btn btn-success btn-lg">Search</button>
        </form>
    {% for x in story %}
        <div class=" mt-3">
            <a href="{{ x.get_absolute_url }}" class="link-secondary"><h4>{{ x.title }}</h4></a>
        <p class="link-primary">{{ x.des }}</p>
        </div>
    {% endfor %}<hr>
        <h3 class="text-center " >{% include 'pagination.html' with page=story %}</h3>
        <hr>
        <h3>Recent two stories:</h3>
    {% for x in recent_story %}
        <a href="{{ x.get_absolute_url }}">
        <h6>{{ x.title }}</h6>
        </a>
    {% endfor %}
    </div>
    </div>
{% endblock %}

templates/test.html
<!DOCTYPE html>
<html>
<head>
  <script
    type="text/javascript"
    src='https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js'
    referrerpolicy="origin">
  </script>
  <script type="text/javascript">
  tinymce.init({
    selector: '#myTextarea',
    width: 600,
    height: 300,
    plugins: [
      'advlist autolink link image lists charmap print preview hr anchor pagebreak',
      'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
      'table emoticons template paste help'
    ],
    toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | ' +
      'bullist numlist outdent indent | link image | print preview media fullpage | ' +
      'forecolor backcolor emoticons | help',
    menu: {
      favs: {title: 'My Favorites', items: 'code visualaid | searchreplace | emoticons'}
    },
    menubar: 'favs file edit view insert format tools table help',
    content_css: 'css/content.css'
  });
  </script>
</head>

<body>
  <textarea id="myTextarea"></textarea>
</body>
</html>